/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/models/punk2.gltf 
*/

import React from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";
import { Bloom, EffectComposer } from "@react-three/postprocessing";

export function Punk(props) {
  const { nodes, materials } = useGLTF("/models/punkpunk.gltf");

  return (
    <group {...props} dispose={null}>
      <group
        name="Cube"
        position={[5.66, 1.985, 2.637]}
        scale={[1.848, 1.926, 1.341]}
      >
        <mesh
          name="Cube_1"
          geometry={nodes.Cube_1.geometry}
          material={materials.Material}
        />
        <mesh
          name="Cube_2"
          geometry={nodes.Cube_2.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          name="Cube_3"
          geometry={nodes.Cube_3.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          name="Cube_4"
          geometry={nodes.Cube_4.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          name="Cube_5"
          geometry={nodes.Cube_5.geometry}
          material={materials.NEON}
        />
      </group>
      <mesh
        name="Cylinder"
        geometry={nodes.Cylinder.geometry}
        material={nodes.Cylinder.material}
        position={[7.774, 0.248, 2.483]}
        scale={[0.018, 0.177, 0.022]}
      />
      <mesh
        name="Cylinder001"
        geometry={nodes.Cylinder001.geometry}
        material={nodes.Cylinder001.material}
        position={[7.774, 0.248, 1.679]}
        scale={[0.018, 0.177, 0.022]}
      />
      <mesh
        name="Cylinder002"
        geometry={nodes.Cylinder002.geometry}
        material={materials["Material.006"]}
        position={[7.774, 0.248, 2.766]}
        scale={[0.018, 0.177, 0.022]}
      />
      <mesh
        name="Cylinder003"
        geometry={nodes.Cylinder003.geometry}
        material={nodes.Cylinder003.material}
        position={[7.774, 0.248, 2.623]}
        scale={[0.018, 0.177, 0.022]}
      />
      <mesh
        name="Cylinder004"
        geometry={nodes.Cylinder004.geometry}
        material={nodes.Cylinder004.material}
        position={[7.774, 0.248, 1.385]}
        scale={[0.018, 0.177, 0.022]}
      />
      <mesh
        name="Cylinder005"
        geometry={nodes.Cylinder005.geometry}
        material={nodes.Cylinder005.material}
        position={[7.774, 0.248, 2.335]}
        scale={[0.018, 0.177, 0.022]}
      />
      <mesh
        name="Cylinder006"
        geometry={nodes.Cylinder006.geometry}
        material={nodes.Cylinder006.material}
        position={[7.774, 0.248, 2.17]}
        scale={[0.018, 0.177, 0.022]}
      />
      <mesh
        name="Cylinder007"
        geometry={nodes.Cylinder007.geometry}
        material={nodes.Cylinder007.material}
        position={[7.774, 0.248, 1.526]}
        scale={[0.018, 0.177, 0.022]}
      />
      <mesh
        name="Cylinder008"
        geometry={nodes.Cylinder008.geometry}
        material={nodes.Cylinder008.material}
        position={[7.774, 0.248, 2.001]}
        scale={[0.018, 0.177, 0.022]}
      />
      <mesh
        name="Cylinder009"
        geometry={nodes.Cylinder009.geometry}
        material={nodes.Cylinder009.material}
        position={[7.774, 0.248, 1.833]}
        scale={[0.018, 0.177, 0.022]}
      />
      <mesh
        name="Cylinder010"
        geometry={nodes.Cylinder010.geometry}
        material={nodes.Cylinder010.material}
        position={[7.445, 2.877, 4.719]}
        scale={[0.018, 0.177, 0.022]}
      />
      <mesh
        name="Cylinder011"
        geometry={nodes.Cylinder011.geometry}
        material={nodes.Cylinder011.material}
        position={[3.869, 2.877, 4.719]}
        scale={[0.018, 0.177, 0.022]}
      />
      <mesh
        name="Cylinder012"
        geometry={nodes.Cylinder012.geometry}
        material={nodes.Cylinder012.material}
        position={[7.009, 2.877, 4.719]}
        scale={[0.018, 0.177, 0.022]}
      />
      <mesh
        name="Cylinder013"
        geometry={nodes.Cylinder013.geometry}
        material={nodes.Cylinder013.material}
        position={[6.792, 2.877, 4.719]}
        scale={[0.018, 0.177, 0.022]}
      />
      <mesh
        name="Cylinder014"
        geometry={nodes.Cylinder014.geometry}
        material={nodes.Cylinder014.material}
        position={[6.571, 2.877, 4.719]}
        scale={[0.018, 0.177, 0.022]}
      />
      <mesh
        name="Cylinder015"
        geometry={nodes.Cylinder015.geometry}
        material={nodes.Cylinder015.material}
        position={[6.355, 2.877, 4.719]}
        scale={[0.018, 0.177, 0.022]}
      />
      <mesh
        name="Cylinder016"
        geometry={nodes.Cylinder016.geometry}
        material={nodes.Cylinder016.material}
        position={[6.133, 2.877, 4.719]}
        scale={[0.018, 0.177, 0.022]}
      />
      <mesh
        name="Cylinder017"
        geometry={nodes.Cylinder017.geometry}
        material={nodes.Cylinder017.material}
        position={[5.492, 2.877, 4.719]}
        scale={[0.018, 0.177, 0.022]}
      />
      <mesh
        name="Cylinder018"
        geometry={nodes.Cylinder018.geometry}
        material={nodes.Cylinder018.material}
        position={[7.231, 2.877, 4.719]}
        scale={[0.018, 0.177, 0.022]}
      />
      <mesh
        name="Cylinder019"
        geometry={nodes.Cylinder019.geometry}
        material={nodes.Cylinder019.material}
        position={[5.274, 2.877, 4.719]}
        scale={[0.018, 0.177, 0.022]}
      />
      <mesh
        name="Cylinder020"
        geometry={nodes.Cylinder020.geometry}
        material={nodes.Cylinder020.material}
        position={[5.067, 2.877, 4.719]}
        scale={[0.018, 0.177, 0.022]}
      />
      <mesh
        name="Cylinder021"
        geometry={nodes.Cylinder021.geometry}
        material={nodes.Cylinder021.material}
        position={[4.85, 2.877, 4.719]}
        scale={[0.018, 0.177, 0.022]}
      />
      <mesh
        name="Cylinder022"
        geometry={nodes.Cylinder022.geometry}
        material={nodes.Cylinder022.material}
        position={[4.654, 2.877, 4.719]}
        scale={[0.018, 0.177, 0.022]}
      />
      <mesh
        name="Cylinder023"
        geometry={nodes.Cylinder023.geometry}
        material={nodes.Cylinder023.material}
        position={[4.441, 2.877, 4.719]}
        scale={[0.018, 0.177, 0.022]}
      />
      <mesh
        name="Cylinder024"
        geometry={nodes.Cylinder024.geometry}
        material={nodes.Cylinder024.material}
        position={[5.913, 2.877, 4.719]}
        scale={[0.018, 0.177, 0.022]}
      />
      <mesh
        name="Cylinder025"
        geometry={nodes.Cylinder025.geometry}
        material={nodes.Cylinder025.material}
        position={[5.7, 2.877, 4.719]}
        scale={[0.018, 0.177, 0.022]}
      />
      <mesh
        name="Cylinder026"
        geometry={nodes.Cylinder026.geometry}
        material={nodes.Cylinder026.material}
        position={[4.221, 2.877, 4.719]}
        scale={[0.018, 0.177, 0.022]}
      />
      <mesh
        name="Cylinder027"
        geometry={nodes.Cylinder027.geometry}
        material={nodes.Cylinder027.material}
        position={[4.034, 2.877, 4.719]}
        scale={[0.018, 0.177, 0.022]}
      />
      <mesh
        name="Cylinder028"
        geometry={nodes.Cylinder028.geometry}
        material={nodes.Cylinder028.material}
        position={[3.869, 2.877, 4.271]}
        scale={[0.018, 0.177, 0.022]}
      />
      <mesh
        name="Cylinder029"
        geometry={nodes.Cylinder029.geometry}
        material={nodes.Cylinder029.material}
        position={[3.869, 2.877, 4.077]}
        scale={[0.018, 0.177, 0.022]}
      />
      <mesh
        name="Cylinder030"
        geometry={nodes.Cylinder030.geometry}
        material={nodes.Cylinder030.material}
        position={[3.869, 2.877, 4.445]}
        scale={[0.018, 0.177, 0.022]}
      />
      <mesh
        name="Cylinder031"
        geometry={nodes.Cylinder031.geometry}
        material={nodes.Cylinder031.material}
        position={[3.869, 2.877, 4.606]}
        scale={[0.018, 0.177, 0.022]}
      />
      <mesh
        name="Cylinder032"
        geometry={nodes.Cylinder032.geometry}
        material={nodes.Cylinder032.material}
        position={[7.449, 2.877, 4.271]}
        scale={[0.018, 0.177, 0.022]}
      />
      <mesh
        name="Cylinder033"
        geometry={nodes.Cylinder033.geometry}
        material={nodes.Cylinder033.material}
        position={[7.449, 2.877, 4.077]}
        scale={[0.018, 0.177, 0.022]}
      />
      <mesh
        name="Cylinder034"
        geometry={nodes.Cylinder034.geometry}
        material={nodes.Cylinder034.material}
        position={[7.449, 2.877, 4.445]}
        scale={[0.018, 0.177, 0.022]}
      />
      <mesh
        name="Cylinder035"
        geometry={nodes.Cylinder035.geometry}
        material={nodes.Cylinder035.material}
        position={[7.449, 2.877, 4.606]}
        scale={[0.018, 0.177, 0.022]}
      />
      <mesh
        name="Cube001"
        geometry={nodes.Cube001.geometry}
        material={materials["Material.007"]}
        position={[5.663, 3.03, 4.713]}
        scale={[1.817, 0.032, 1]}
      />
      <mesh
        name="Greeble_Cables_Pack1011"
        geometry={nodes.Greeble_Cables_Pack1011.geometry}
        material={materials.Basic_Render_Material}
        position={[5.98, 3.982, 1.914]}
        rotation={[Math.PI, -1.564, Math.PI]}
        scale={0.131}
      />
      <mesh
        name="Greeble_Cables_Pack1037"
        geometry={nodes.Greeble_Cables_Pack1037.geometry}
        material={materials.Basic_Render_Material}
        position={[7.533, 1.296, 2.285]}
        rotation={[2.721, 0, -1.627]}
        scale={0.197}
      />
      <mesh
        name="Greeble_Cables_Pack1040"
        geometry={nodes.Greeble_Cables_Pack1040.geometry}
        material={materials.Basic_Render_Material}
        position={[6.117, 1.082, 4.009]}
        rotation={[-1.104, 1.559, 2.674]}
        scale={0.198}
      />
      <group
        name="HVAC_Single"
        position={[7.542, 0.869, 2.561]}
        rotation={[-Math.PI, 1.569, -Math.PI]}
        scale={0.314}
      >
        <mesh
          name="Cube016"
          geometry={nodes.Cube016.geometry}
          material={materials["Basic Grey"]}
        />
        <mesh
          name="Cube016_1"
          geometry={nodes.Cube016_1.geometry}
          material={materials["Rough Metal Light"]}
        />
        <mesh
          name="Cube016_2"
          geometry={nodes.Cube016_2.geometry}
          material={materials["vent grid"]}
        />
        <mesh
          name="Cube016_3"
          geometry={nodes.Cube016_3.geometry}
          material={materials["Raw Metal"]}
        />
      </group>
      <group name="HVAC_Double" position={[4.573, 3.751, 3.935]} scale={0.263}>
        <mesh
          name="Cube006"
          geometry={nodes.Cube006.geometry}
          material={materials["Basic Grey"]}
        />
        <mesh
          name="Cube006_1"
          geometry={nodes.Cube006_1.geometry}
          material={materials["Rough Metal Light"]}
        />
        <mesh
          name="Cube006_2"
          geometry={nodes.Cube006_2.geometry}
          material={materials["vent grid"]}
        />
        <mesh
          name="Cube006_3"
          geometry={nodes.Cube006_3.geometry}
          material={materials["Raw Metal"]}
        />
      </group>
      <mesh
        name="Ext_Vent_01"
        geometry={nodes.Ext_Vent_01.geometry}
        material={materials["Rough Metal Light"]}
        position={[5.244, 3.998, 3.546]}
        rotation={[-1.571, 0, 0]}
        scale={[0.158, 0.113, 0.158]}
      />
      <group
        name="Rooftop_Vents002"
        position={[6.277, 3.881, 2.664]}
        scale={0.237}
      >
        <mesh
          name="Hong_Kong_Skyline_(249)008"
          geometry={nodes["Hong_Kong_Skyline_(249)008"].geometry}
          material={materials["Basic Grey"]}
        />
        <mesh
          name="Hong_Kong_Skyline_(249)008_1"
          geometry={nodes["Hong_Kong_Skyline_(249)008_1"].geometry}
          material={materials["vent grid"]}
        />
        <mesh
          name="Hong_Kong_Skyline_(249)008_2"
          geometry={nodes["Hong_Kong_Skyline_(249)008_2"].geometry}
          material={materials["Rough Metal"]}
        />
      </group>
      <group
        name="Rooftop_Vents004"
        position={[5.473, 0.013, 4.285]}
        rotation={[0, 1.565, 0]}
        scale={0.448}
      >
        <mesh
          name="Hong_Kong_Skyline_(249)011"
          geometry={nodes["Hong_Kong_Skyline_(249)011"].geometry}
          material={materials["Basic Grey"]}
        />
        <mesh
          name="Hong_Kong_Skyline_(249)011_1"
          geometry={nodes["Hong_Kong_Skyline_(249)011_1"].geometry}
          material={materials["vent grid"]}
        />
        <mesh
          name="Hong_Kong_Skyline_(249)011_2"
          geometry={nodes["Hong_Kong_Skyline_(249)011_2"].geometry}
          material={materials["Rough Metal"]}
        />
      </group>
      <mesh
        name="Curve"
        geometry={nodes.Curve.geometry}
        material={materials.NEON}
        position={[7.531, 2.152, 3.998]}
        rotation={[1.572, 0.01, -1.586]}
        scale={[2.534, 2.562, 2.562]}
      />
      <mesh
        name="Ext_Vent_01001"
        geometry={nodes.Ext_Vent_01001.geometry}
        material={materials["Rough Metal Light"]}
        position={[7.094, 3.998, 3.546]}
        rotation={[-1.571, 0, 0]}
        scale={[0.158, 0.113, 0.158]}
      />
      <mesh
        name="Plane"
        geometry={nodes.Plane.geometry}
        material={materials["Material.009"]}
        position={[6.377, 0, 2.936]}
        scale={-3.099}
      />
    </group>
  );
}

useGLTF.preload("/models/punkpunk.gltf");
